#!/bin/bash

if [ ! -d /usr/local/src/.venv/bin ]
then
    python3 -m venv /usr/local/src/.venv
    /usr/local/src/.venv/bin/pip3 install -v wheel
    /usr/local/src/.venv/bin/pip3 install -v uwsgi dash dash_bootstrap_components pymongo
fi
