#!/bin/bash

cp /usr/local/src/nginx.conf /etc/nginx/nginx.conf
cp /usr/local/src/sumerians-to-greek /etc/init.d/sumerians-to-greek
cp /usr/local/src/mongod /etc/init.d/mongod
cp /usr/local/src/mongod.conf /etc/mongod.conf

if [ ! -d /var/log/uwsgi ]
then
    mkdir /var/log/uwsgi
fi

if [ ! -e /var/log/uwsgi/uwsgi.log ]
then
    touch /var/log/uwsgi/uwsgi.log
fi

update-rc.d sumerians-to-greek defaults
update-rc.d mongod defaults
