#!/bin/bash

WD=/usr/local/src/sumerians-to-greek/work_folder
VENV=$WD/.venv
BIN=$VENV/bin
PIP=$BIN/pip3

if [ ! -d $BIN ]
then
    python3 -m venv $VENV
    $PIP install -v wheel
    $PIP install -v uwsgi dash dash_bootstrap_components pymongo
fi
