#!/bin/bash

apt-get update -y
apt-get upgrade -y

apt-get install -y wget gnupg
wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -

echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" \
    | tee /etc/apt/sources.list.d/mongodb-org-5.0.list

apt-get update -y

apt-get install -y \
    openssl \
    gnupg2 \
    ca-certificates \
    lsb-release \
    git \
    curl \
    python3 \
    python3-pip \
    python3-venv \
    mongodb-org

echo "deb http://nginx.org/packages/debian `lsb_release -cs` nginx" \
    | tee /etc/apt/sources.list.d/nginx.list

curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
apt-get update -y
apt-get install nginx
