#!/bin/bash

PID=/usr/local/src/sumerians-to-greek/work_folder/mongodb.pid

do_start()
{
    echo "Starting mongoDB"
    mongod --config /etc/mongod.conf --fork --profile=2 --slowms=1 -vv
}

do_stop()
{
    echo "Stopping mongoDB"

    if [ -e $PID ]
    then
        kill -INT $(cat $PID)
    fi
}

case "$1" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    *)
        echo "Inavlid argument"
        exit 1
        ;;
esac

exit 0
