#!/bin/bash

do_start()
{
    echo "Starting mongoDB"
    mongod --config /etc/mongod.conf --fork --profile=2 --slowms=1 -vv
}

do_stop()
{
    echo "Stopping mongoDB"

    if [ -e /usr/local/src/mongodb.pid ]
    then
        kill -INT `/usr/local/src/mongodb.pid`
    fi
}

case "$1" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    restart)
        do_stop
        do_start
        ;;
    *)
        echo "Inavlid argument"
        exit 1
        ;;
esac

exit 0
