#!/bin/bash

SG=/usr/local/src/sumerians-to-greek
WD=$SG/work_folder
DB=$SG/db
SHOULD_CREATE_DB=0

$WD/install-python-packages

if [ $? -ne 0 ]
then
    echo "Не удалось установить пакеты"
    exit 1
fi

$WD/setup-services

if [ $? -ne 0 ]
then
    echo "Не удалось настроить сервисы"
    exit 1
fi

if [ ! -d $DB ]
then
    mkdir $DB
    SHOULD_CREATE_DB=1
fi

echo "Запускаю MongoDB"
service mongod start

if [ $? -ne 0 ]
then
    echo "Не удалось запустить MongoDB"
    exit 1
fi

if [ $SHOULD_CREATE_DB -eq 1 ]
then
    $WD/create-db

    if [ $? -ne 0 ]
    then
        echo "Не удалось создать базу данных"
        exit 1
    fi
fi

echo "Запускаю uwsgi"
service sumerians-to-greek start

if [ $? -ne 0 ]
then
    echo "Не удалось запустить uwsgi"
    exit 1
fi

echo "Запускаю nginx"
service nginx start

if [ $? -ne 0 ]
then
    echo "Не удалось запустить nginx"
    exit 1
fi
