#!/bin/bash

WD=/usr/local/src/sumerians-to-greek/work_folder
UWSGI=$WD/.venv/bin/uwsgi
PID=$WD/uwsgi.pid

do_start()
{
    echo "Starting application"
    cd $WD && $UWSGI --ini $WD/uwsgi.ini
}

do_stop()
{
    echo "Stopping application"

    if [ -e $PID ]
    then
        $UWSGI --stop $PID
    fi
}

case "$1" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    *)
        echo "Inavlid argument"
        exit 1
        ;;
esac

exit 0
